### ISSUE TITLE
RwLock is unsound

### ISSUE THREAD

**Issue by Darksonn** [asomers/futures-locks#37]
By creating multiple read guards and sending them to different threads, you can obtain multiple shared references to a non-Sync value in different threads.

This impl should require `Sync`:
```rust
impl<T: ?Sized> Send for RwLockReadGuard<T> where
    T: Send, 
```

**Comment by jplatte** [comment]
This impl doesn't seem to exist anymore. The only `Send` impls are for `MutexWeak`, `Mutex` and `RwLock`.

I noticed though that this library only requires `Send` for the `Sync` impl of `RwLock` where tokio requires `Send + Sync`. Unfortunately the comment in tokio only explains why `Send` is required, but the tokio bounds are the same as the `std` bounds, so maybe it is required?

**Comment by Darksonn** [comment]
If you have an `RwLock<T>` that implements `Sync` for a non-Sync type `T`, then you can send an `&RwLock<T>` to many threads, lock it with a read lock on each thread, and get parallel immutable access to the `T`, in violation with `T` not being `Sync`.
