### ISSUE TITLE
Release 0.5.1

### ISSUE THREAD

**Issue by itpetey** [asomers/futures-locks#38]
Is it possible to release 0.5.1 soon? I am blocked behind the updates to Tokio 0.2 etc. which haven't made their way to Crates yet. Is there anything outstanding that you need help with?

**Comment by asomers** [comment]
Are you wanting to use futures-locks with std::future ?

**Comment by itpetey** [comment]
Sorry for the delay, moving country! Yep that's right.

**Comment by itpetey** [comment]
Gentle bump :)

**Comment by asomers-ax** [comment]
Sorry; I've just been too busy between work and (home) school.  I'll try to do make a release this weekend.

**Comment by itpetey** [comment]
No need to apologise mate. Thanks very much for your efforts!

Have you considered automating releases with a GH workflow? I'd be happy to contribute something if that's the way you want to go.

**Comment by asomers** [comment]
Done.  Except it's 0.6.0, not 0.5.1.
