### ISSUE TITLE
tokio's current_thread::spawn can fail in multithreaded environment

### ISSUE THREAD

**Issue by Keruspe** [asomers/futures-locks#5]
When using `tokio::runtime::current_thread::Runtime` everything works as expected but when using `tokio::runtime::Runtime` I get failures such as:

```
 panicked at '  called `Result::unwrap()` on an `Err` value: SpawnError { is_shutdown: true } 
```

caused by

```
  10: tokio::executor::current_thread::spawn                                                                           
             at /home/keruspe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.7/src/executor/current_thread/mod.rs:294
  11: <futures_locks::mutex::Mutex<T>>::with                                                                              
             at /home/keruspe/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-locks-0.2.1/src/mutex.rs:340    
```

Any reason not to just use `tokio_executor::spawn()`? (it would lower the tokio dependency to only tokio-executor, and grab the current execution context, be it mono or multi threaded)

**Comment by asomers** [comment]
Good idea, but there are two problems:
1) `tokio_executor::spawn` requires the Future to be `Send`.  `current_thread::spawn` does not.  Should I have a separate version of the `with` method for non-`Send` Futures that can only execute on the current thread?
2) Using `tokio_executor::spawn` seems to work if I create the runtime using either `runtime::Runtime::new()` or `runtime::current_thread::Runtime::new()`.  However, if I use `tokio::executor::current_thread::block_on_all`, then I get a `SpawnError { is_shutdown: true }`.  Do you know what's going on?  Is `tokio::executor::current_thread::block_on_all` deprecated?

**Comment by Keruspe** [comment]
Hmm

1. Is that really a problem? Pretty much all of tokio requires futures to be Send anyway, I guess CurrentThread might be the exception

2. From what I understood, CurrentThread was the way to go when there was no monothreaded Runtime, now that there's one, using it + spawn is the preferred way to go, but I might be missing something.

I'd say with should work with Runtime (which is what you get when using e.g. tokio::run) and maybe add another alternative that works with CurrentThread if needed?

**Comment by asomers** [comment]
I'll open an issue at Tokio to get some clarification on using `tokio::executor::current_thread::block_on_all` with `tokio_executor::spawn`.  As for the `Send` vs non-`Send` methods, I agree that `Send` is probably a more sensible default.  But what do you think the non-`Send` versions should be called?  `with_st`, `with_single_thread`, `with_local`, or something else?  Are you aware of any good precedent?

**Comment by Keruspe** [comment]
`with_local` LGTM, reminds of `thread_local` stuff

**Comment by Keruspe** [comment]
Related : https://github.com/tokio-rs/tokio/issues/382

**Comment by asomers** [comment]
I've opened https://github.com/tokio-rs/tokio/issues/440 , and I'm going to to wait on this issue until that one has a resolution.

**Comment by Keruspe** [comment]
Maybe the right call here is to wait for the next tokio release and just use `tokio::runtime::Runtime::new().unwrap().block_on_all()` instead of `tokio::executor::current_thread::block_on_all()`?
