### ISSUE TITLE
Guard types don't have a lifetime parameter

### ISSUE THREAD

**Issue by jplatte** [asomers/futures-locks#50]
I don't know whether this is actually a problem, but I noticed that in contrast to all of [std::sync, async-lock, tokio::sync], the lock guards from this crate don't have lifetime parameters.

**Comment by asomers** [comment]
That's because futures-locks's guards are `'static`.  It was a nearly absolute requirement with Tokio 0.1.  Now that async/await is here it's no longer as important, but it's still useful for many cases.

**Comment by jplatte** [comment]
I see. This makes it impossible to create a re-export / type alias of either `tokio::MutexGuard` or `futures_locks::MutexGuard` to use with different `cfg`s, but oh well. I'll try `async-lock`, it has a dev-dependency on `wasm-bindgen-test` so should support WASM as well.
