### ISSUE TITLE
Include tests in crates.io upload

### ISSUE THREAD

**Issue by werdahias** [asomers/futures-locks#52]
I just noticed that this repo includes tests under the `tests` folder, those aren't included in the upload to crates.io. Please consider including them.

Cheers

**Comment by asomers** [comment]
Who would ever use them, when downloading from crates.io ?

**Comment by werdahias** [comment]
I packaged your crate for Debian/ubuntu. The testsuite that is running for it will fail if the testdata isn't present during compilation.

**Comment by asomers** [comment]
Hmm, ok.  That's a valid reason.  But also, why does Debian need a package for this crate?  FreeBSD, at least, does not need packages for library crates.  Did you need to patch this crate to make it work on Debian?

**Comment by werdahias** [comment]
The debian rust crate provides only the library files as-is. debian policy requires that all libraries (i.e. crates are packaged before compiling a program that uses them.

**Comment by asomers** [comment]
Released as 0.7.1
